"""Proactive alert system — models and in-memory store with deduplication."""
from __future__ import annotations

import time
import uuid
from collections import OrderedDict
from dataclasses import dataclass, field
from enum import Enum
from threading import Lock


class AlertSeverity(str, Enum):
    CRITICAL = "critical"
    ELEVATED = "elevated"
    NORMAL = "normal"


@dataclass
class Alert:
    """A proactive alert generated by pattern detection."""
    alert_type: str
    severity: AlertSeverity
    title: str
    description: str
    lat: float | None = None
    lng: float | None = None
    data: dict = field(default_factory=dict)
    created_at: float = 0.0
    alert_id: str = ""
    # Significance scoring (EXP-024/027) — None if no profile registered
    significance: int | None = None
    signal_score: float | None = None
    routine_score: float | None = None


class AlertStore:
    """Thread-safe in-memory alert store with LRU eviction, TTL, and dedup."""

    def __init__(
        self,
        max_alerts: int = 200,
        ttl_seconds: float = 7200,
        dedup_cooldown_seconds: float = 300,
    ):
        self._max = max_alerts
        self._ttl = ttl_seconds
        self._dedup_cooldown = dedup_cooldown_seconds
        self._store: OrderedDict[str, Alert] = OrderedDict()
        self._dedup_keys: dict[str, float] = {}  # dedup_key -> last_saved_time
        self._lock = Lock()

    def _dedup_key(self, alert: Alert) -> str:
        lat = round(alert.lat, 1) if alert.lat is not None else "none"
        lng = round(alert.lng, 1) if alert.lng is not None else "none"
        return f"{alert.alert_type}:{lat}:{lng}"

    def save(self, alert: Alert) -> str | None:
        """Save an alert. Returns alert_id, or None if deduplicated."""
        now = time.time()

        with self._lock:
            # Dedup check
            dk = self._dedup_key(alert)
            last_time = self._dedup_keys.get(dk)
            if last_time is not None and (now - last_time) < self._dedup_cooldown:
                return None

            aid = uuid.uuid4().hex[:12]
            alert.alert_id = aid
            alert.created_at = now

            self._store[aid] = alert
            self._dedup_keys[dk] = now

            # Evict oldest if over capacity
            while len(self._store) > self._max:
                self._store.popitem(last=False)

            # Clean old dedup keys
            expired = [k for k, t in self._dedup_keys.items()
                       if now - t > self._dedup_cooldown]
            for k in expired:
                del self._dedup_keys[k]

        return aid

    def get(self, alert_id: str) -> Alert | None:
        """Retrieve an alert by ID, or None if missing/expired."""
        with self._lock:
            alert = self._store.get(alert_id)
            if alert is None:
                return None
            if time.time() - alert.created_at > self._ttl:
                del self._store[alert_id]
                return None
            return alert

    def list(self, limit: int = 50) -> list[dict]:
        """List alert metadata, newest first."""
        now = time.time()
        result = []
        with self._lock:
            for aid, alert in reversed(self._store.items()):
                if now - alert.created_at > self._ttl:
                    continue
                result.append({
                    "id": aid,
                    "alert_type": alert.alert_type,
                    "severity": alert.severity.value,
                    "title": alert.title,
                    "description": alert.description,
                    "lat": alert.lat,
                    "lng": alert.lng,
                    "created_at": alert.created_at,
                    "significance": alert.significance,
                    "signal_score": alert.signal_score,
                    "routine_score": alert.routine_score,
                })
                if len(result) >= limit:
                    break
        return result


# Global singleton
_alert_store: AlertStore | None = None


def get_alert_store() -> AlertStore:
    global _alert_store
    if _alert_store is None:
        _alert_store = AlertStore()
    return _alert_store
