"""Artifact storage — holds agent-generated HTML artifacts with TTL eviction."""
from __future__ import annotations

import time
import uuid
from collections import OrderedDict
from dataclasses import dataclass, field
from threading import Lock


@dataclass
class Artifact:
    """A self-contained HTML artifact generated by an agent."""
    html: str
    title: str = ""
    query: str = ""
    artifact_type: str = ""
    created_at: float = 0.0


class ArtifactStore:
    """Thread-safe in-memory artifact store with LRU eviction and TTL."""

    def __init__(self, max_artifacts: int = 50, ttl_seconds: float = 3600):
        self._max = max_artifacts
        self._ttl = ttl_seconds
        self._store: OrderedDict[str, Artifact] = OrderedDict()
        self._lock = Lock()

    def save(self, artifact: Artifact) -> str:
        """Save an artifact and return its ID."""
        aid = uuid.uuid4().hex[:12]
        artifact.created_at = time.time()

        with self._lock:
            self._store[aid] = artifact
            # Evict oldest if over capacity
            while len(self._store) > self._max:
                self._store.popitem(last=False)

        return aid

    def get(self, artifact_id: str) -> Artifact | None:
        """Retrieve an artifact by ID, or None if missing/expired."""
        with self._lock:
            art = self._store.get(artifact_id)
            if art is None:
                return None
            if time.time() - art.created_at > self._ttl:
                del self._store[artifact_id]
                return None
            return art

    def list(self) -> list[dict]:
        """List artifact metadata (no html bodies)."""
        now = time.time()
        result = []
        with self._lock:
            for aid, art in self._store.items():
                if now - art.created_at <= self._ttl:
                    result.append({
                        "id": aid,
                        "title": art.title,
                        "query": art.query,
                        "artifact_type": art.artifact_type,
                        "created_at": art.created_at,
                    })
        return result


# Global singleton
_artifact_store: ArtifactStore | None = None


def get_artifact_store() -> ArtifactStore:
    global _artifact_store
    if _artifact_store is None:
        _artifact_store = ArtifactStore()
    return _artifact_store
