import type { ActiveLayers } from "@/types/dashboard";

export type PresetKey = "OVERVIEW" | "MARITIME" | "AVIATION" | "CONFLICT" | "INFRA" | "ALL";

const OFF: ActiveLayers = {
  flights: false,
  private: false,
  jets: false,
  military: false,
  tracked: false,
  satellites: false,
  ships_military: false,
  ships_cargo: false,
  ships_civilian: false,
  ships_passenger: false,
  ships_tracked_yachts: false,
  earthquakes: false,
  cctv: false,
  ukraine_frontline: false,
  global_incidents: false,
  day_night: false,
  gps_jamming: false,
  gibs_imagery: false,
  highres_satellite: false,
  kiwisdr: false,
  firms: false,
  internet_outages: false,
  datacenters: false,
  military_bases: false,
  power_plants: false,
  prediction_markets: false,
  ukraine_alerts: false,
  fimi: false,
  trains: false,
  meshtastic: false,
};

export const PRESETS: Record<PresetKey, { label: string; layers: ActiveLayers }> = {
  OVERVIEW: {
    label: "OVERVIEW",
    layers: {
      ...OFF,
      flights: true,
      jets: true,
      military: true,
      tracked: true,
      satellites: true,
      ships_military: true,
      ships_tracked_yachts: true,
      earthquakes: true,
      ukraine_frontline: true,
      global_incidents: true,
      day_night: true,
      gps_jamming: true,
      highres_satellite: true,
      prediction_markets: true,
      ukraine_alerts: true,
    },
  },
  MARITIME: {
    label: "MARITIME",
    layers: {
      ...OFF,
      ships_military: true,
      ships_cargo: true,
      ships_civilian: true,
      ships_passenger: true,
      ships_tracked_yachts: true,
      day_night: true,
      highres_satellite: true,
    },
  },
  AVIATION: {
    label: "AVIATION",
    layers: {
      ...OFF,
      flights: true,
      private: true,
      jets: true,
      military: true,
      tracked: true,
      gps_jamming: true,
      day_night: true,
      highres_satellite: true,
    },
  },
  CONFLICT: {
    label: "CONFLICT",
    layers: {
      ...OFF,
      military: true,
      tracked: true,
      ships_military: true,
      ukraine_frontline: true,
      global_incidents: true,
      gps_jamming: true,
      military_bases: true,
      firms: true,
      day_night: true,
      highres_satellite: true,
      prediction_markets: true,
      ukraine_alerts: true,
      fimi: true,
    },
  },
  INFRA: {
    label: "INFRA",
    layers: {
      ...OFF,
      datacenters: true,
      power_plants: true,
      internet_outages: true,
      kiwisdr: true,
      firms: true,
      trains: true,
      day_night: true,
      highres_satellite: true,
    },
  },
  ALL: {
    label: "ALL",
    layers: {
      flights: true,
      private: true,
      jets: true,
      military: true,
      tracked: true,
      satellites: true,
      ships_military: true,
      ships_cargo: true,
      ships_civilian: true,
      ships_passenger: true,
      ships_tracked_yachts: true,
      earthquakes: true,
      cctv: true,
      ukraine_frontline: true,
      global_incidents: true,
      day_night: true,
      gps_jamming: true,
      gibs_imagery: false,
      highres_satellite: true,
      kiwisdr: true,
      firms: true,
      internet_outages: true,
      datacenters: true,
      military_bases: true,
      power_plants: true,
      prediction_markets: true,
      ukraine_alerts: true,
      fimi: true,
      trains: true,
      meshtastic: true,
    },
  },
};

export const DEFAULT_LAYERS = PRESETS.OVERVIEW.layers;
